title: 'Application Form'
honeypot: webs1te
email:
  -
    id: lptkqymo
    to: m@marceli.to
    from: no-reply@mihmfoundation.ch
    reply_to: no-reply@mihmfoundation.ch
    subject: 'Antragsformular mihmfoundation.ch'
    html: templates/email/html/application
    text: templates/email/text/application
