tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: teaser
            field:
              antlers: false
              type: textarea
              display: Teaser
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: text
            field:
              buttons:
                - bold
                - unorderedlist
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Text
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: facts
            field:
              antlers: false
              type: textarea
              display: Facts
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  media:
    display: Media
    sections:
      -
        display: Media
        fields:
          -
            handle: image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Image
              icon: assets
              instructions: 'Main Image used in Slideshow, Project preview and Project detail'
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: video
            field:
              antlers: false
              type: textarea
              display: Video
              icon: textarea
              instructions: 'Add video embed code from Youtube or Vimeo'
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
  quote:
    display: Quote
    sections:
      -
        display: Quote
        fields:
          -
            import: quote
  seo:
    display: SEO
    sections:
      -
        display: 'Neuer Abschnitt'
        fields:
          -
            handle: open_graph_title
            field:
              input_type: text
              antlers: false
              type: text
              display: Title
              icon: text
              instructions: 'Can be used as a replacement for the page title'
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: open_graph_description
            field:
              antlers: false
              type: textarea
              display: Description
              icon: textarea
              instructions: 'One or two descriptive sentences about the content of the page.'
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: open_graph_image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Image
              icon: assets
              instructions: 'Image used for sharing on social media.'
              listable: hidden
              instructions_position: below
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: category
            field:
              options:
                foerderbereich-gesundheit: Gesundheit
                foerderbereich-bildung: Bildung
                foerderbereich-sensebezirk: Sensebezirk
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              default: health
              type: select
              display: Category
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: page_theme
            field:
              options:
                olive: Olive
                burgundy: Burgundy
                terracotta: Terracotta
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              default: '#4B6E5A'
              type: select
              display: Theme
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
title: Project
